[package]
name = "advent_downloader"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
reqwest = { version = "0.11.7",  features = ["blocking"]}
clap = { version = "4.0.29", features = ["derive"] }
bytes = "1.1.0"
chrono = "0.4"
