[package]
name = "advent_downloader"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
reqwest = { version = "0.11.7",  features = ["blocking"]}
clap = "2.34.0"
chrono = "0.4"